<a href="https://colab.research.google.com/github/altn714/ESAA/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.__config__.show()

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
zero_array = np.zeros((10,), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[0 0 0 0 0 0 0 0 0 0]
int32 (10,)


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
array_int = np.array([1,2,3])
array_int.shape

(3,)

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector = np.zeros((10,), dtype='int32')
print(null_vector)
null_vector[4]=1
print(null_vector)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array1 = np.arange(start=10, stop=50) 
print('array1:', array1) 

array1: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
sort_array1_desc = np.sort(array1)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)


내림차순으로 정렬: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array1d =  np.arange(start=0, stop=9)
array2d = array1d.reshape(3, 3)
print(array2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a=[1,2,0,0,4,0]
b=[]
for i in a:
  if i!=0:
    b.append(a.index(i))
print(b)

[0, 1, 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.12577394 0.64058548 0.58975097]
  [0.37026652 0.2307154  0.82163883]
  [0.67392554 0.62367262 0.13600458]]

 [[0.05291684 0.82662844 0.00864054]
  [0.98963175 0.43844789 0.60073493]
  [0.30082653 0.73134845 0.71885069]]

 [[0.24839605 0.99317036 0.71002188]
  [0.80878301 0.87046847 0.87884865]
  [0.82465615 0.4036764  0.71794625]]]


12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 

print("Minimum and Maximum Values:")
print(x.min(), x.max())

Original Array:
[[0.98693806 0.40446785 0.526701   0.16468087 0.01450624 0.46187967
  0.10011665 0.38354783 0.857983   0.73346826]
 [0.1526177  0.62609359 0.55431212 0.16477735 0.60286215 0.45003341
  0.7609462  0.99694344 0.97695621 0.06421658]
 [0.67222642 0.9832191  0.35106508 0.49651444 0.08363701 0.30754912
  0.85759923 0.38961467 0.8480826  0.97803999]
 [0.1230067  0.65029134 0.7051363  0.37568196 0.59168297 0.16299919
  0.36560219 0.60705314 0.71141135 0.54232412]
 [0.95931252 0.81767047 0.27760506 0.56583809 0.87504138 0.82980103
  0.30140286 0.17159179 0.02411864 0.52815584]
 [0.24125412 0.47847768 0.82366995 0.06285529 0.63059355 0.11191293
  0.7943748  0.28751235 0.56678914 0.72584553]
 [0.22066535 0.4279003  0.36497437 0.08015759 0.22424904 0.72316201
  0.27411853 0.55167406 0.97701714 0.7767529 ]
 [0.17898354 0.41846924 0.27522072 0.79457859 0.63484139 0.44524387
  0.67574073 0.81553048 0.05845508 0.53152462]
 [0.91122166 0.8910123  0.29963484 0.52071734 0.91155623 0.23415

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
x = np.random.random((30,))
print(x)
print('mean value: \n', x.mean())

[0.88655895 0.05494509 0.7953277  0.45652439 0.92557444 0.61594407
 0.90425909 0.91244967 0.61609971 0.67328428 0.00834967 0.08969181
 0.24957788 0.62948697 0.93307891 0.48225293 0.61911403 0.425622
 0.49960772 0.15936993 0.33767881 0.84847617 0.72958338 0.25488269
 0.83112811 0.50695478 0.93329139 0.6390212  0.26466804 0.5647203 ]
mean value: 
 0.5615841368997417


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
v=np.ones((10,10))
v[1:-1,1:-1]=0
v

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
A = np.zeros((8,8))
A[1:8:2, 1:8:2] = 1 #1부터 8까지 2씩 건너뛰어서 1으로 수정, 분배법칙 (1,3,5,7) (1,3,5,7) -> ((1,1),(1,3),(1,5),(1,7)),((3,1),()
A[0:7:2, 0:7:2] = 1 
A

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
print(np.unravel_index(100,(6,7,8)))

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
Z= np.dot(np.ones((5,3)), np.ones((3,2)))
print (Z)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
def generate(): 
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(), dtype=float, count=-1)
print (Z)

NameError: ignored

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [2]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

NameError: ignored

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [3]:
Z = np.random.random(10)
Z.sort()
print(Z)

NameError: ignored

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [4]:
Z1 = np.random.randint(0,10,10)
print(Z1)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z2)
print(np.intersect1d(Z1,Z2))

NameError: ignored

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A=np.ones(3)*1
B=np.ones(3)*2
print(A)
print(B)

np.multiply(np.add(A,B),np.divide(np.negative(A),2))

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
c=np.array([1.2, 3.4])
print(c-c%1)
print(c//1)

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
mat=np.zeros((5,5))
mat+=np.arange(5)
print(mat)

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vector = np.random.random(10)
A=vector.sort()
print(A)
print(vector) #두가지방법

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
np.array_equal(A,B)

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1] #X,Y할당
R = np.sqrt(X**2+Y**2)
P = np.arctan2(Y,X)
print(R)
print(P)

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
Z=np.random.random(10)
Z[Z.argmax()]=0   #[]를 넣는방법
print(Z)

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin() #abs는 절대값
print(Z[index])

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)
#여기서 np.ndenumerate:다차원 index 반환 이라는 뜻,
#"(위치) 결과값" 형태로 아웃풋이 나와야한다.
for index, value in np.ndenumerate(Z):
    print(index,value)

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 10
p = 5
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'1')
print(Z)

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)

In [ ]:
# column 1
print(Z[Z[:,0].argsort()])

In [ ]:
# column 2
print(Z[Z[:,1].argsort()])

In [ ]:
# column 3
print(Z[Z[:,2].argsort()])