<a href="https://colab.research.google.com/github/altn714/ESAA/blob/main/22_0916_%EA%B3%BC%EC%A0%9C(%EC%B5%9C%EC%A2%85).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 01. 머신러닝의 개념


*   데이터를 관통하는 패턴 학습 (수학적 
기법을 적용 -> 통계적 신뢰도 결과 도출 및 예측 오류 최소화) 

*   머신러닝 알고리즘 기반의 새로운 예측 모델 이용 -> (1) 정확한 예측 및 의사결정 도출 / (2) 데이터의 새로운 의미와 인사이트 발굴

> ## 머신러닝의 분류
*   지도학습 :  분류, 회귀,추천 시스템,시각/음성 감지/인지, 텍스트 분석 NPL,클러스터링,차원 축소, 강화학습
*   비지도학습
*   강화학습

>## 데이터 전쟁
*   머신러닝 중요 요소: 데이터, 머신러닝 알고리즘 정확도
*   머신러닝의 큰 단점: 데이터에 의존적
*   __결론__: 최적의 머신러닝 알고리즘, 모델 파라미터를 구축하는 능력도 중요 하지만,데이터 이해 & 효율적으로 가공,처리,추출한 최적의 데이터를 기반으로 머신러닝 모델 만들기.

>## 머신러닝 프로그램: __파이썬, R__ 
(C++,JAVA도 가능 but, 파이썬과 R에 비해 개발생산성 떨어짐)

*   R : 통계 전용 프로그램 언어 (SPSS,SAS,MATLAB 통계 및 마이닝 패키지의 고비용 단점 극복)

*   파이썬: 직관적인 문법, 객체지향, 함수형 프로그래밍, 아키텍처, 다양한 라이브러리 (유연함)

# 02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지

*   머신러닝 패키지: 사이킷런(Scikit-Learn) *데이터 마이닝 기반의 머신러닝에서 독보적인 위치

*   행렬/선형대수/통계 패키지: 넘파이(NumPy)

*   데이터 핸들링: 2차원 데이터 처리 특화 *맷플롯립을 호출해 시각화 기능 지원

*   시각화: 맷플롯립 (대표적 시각화 라이브러리) -> 시본 (맷플롯립의 API 이용하여 효율 개선)

*   오픈소스 라이브러리: 편한 해결책 제공
*   주피터 노트북: 예제 소스 구동을 통해서 쉽게 사용법 익힘

## Anaconda 설치:  (직접해야함)
머신러닝을 위한 패키지 모두 설치됨. (넘파이,판다스,맷플롯립,시본,주피터 노트북) 

*   주피터 노트북의 디폴트 디렉터리 'C:/Users/사용자명'


# 배움 목적: 
*   넘파이와 판다스가 머신러닝의 예제에서 데이터 가공에 어떻게  사용되는지
*   기본 프레임워크와 중요 API 습득. 코드로 부딪히기




#03. 넘파이
루프 사용 X, 대량 데이터 배열 빠른 연산, 많은 파이썬 패키지가 넘파이 통해 데이터 처리
단점: 편의성,다양한 API 지원 측면의 단점 *데이터는 2차원 형태의 행과 열로 구성, 다양한 가공과 변환, 통계 함수의 적용이 필요함. -> 판다스의 데이터프레임을 자주 사용할 것

## 넘파이 ndarray 개요


In [ ]:
#np.array() 변환 객체를 인자로 입력 시, ndarray 반환
#ndarray.shape는 ndarray의 차원 크기를 튜플 형태로 나타냄
import numpy as np
array1 =np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) #(3,) 1차원 array로 3개 데이터
array2 = np.array([[1,2,3],
                  [2,3,4]]) #(2,3) 2차원 array로, 2개의 행, 3개의 열 총 6개의 데이터
print('array2 type:', type(array2))
print('array2 array:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape) # array3의 shape는 (1,3) 명확한 2차원 데이터

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


#ndarray.ndim 
:각 array의 차원





In [ ]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

#array1은 1차원 리스트 등등
# 리스트 []는 1차원, 리스트의 리스트[[]]는 2차원


array1: 1차원, array2: 2차원, array3:  2차원


ndarray의 데이터 타입 
*   숫자값 *int형/unsigned int형/float형/complex 타입, 문자열 값, 불 값 모두 가능
*   같은 데이터 타입만 가능



In [ ]:
#데이터 타입 동일
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
#리스트 자료형 list1 은 integer 숫자 1,2,3 가짐. ndarray 내의 데이터 값은 모두 int64형임.

#데이터 타입 다름 
#int와 string 혼합
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) #더 큰 데이터 타입으로 변환 int형 -> 유니코드 문자

#int와 float 혼합
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # float 64형 변환



<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64


# astype() 
*  괄호 안에 인자로 원하는 타입을 문자열로 지정 
*   데이터 타입 변경   



In [ ]:
# int32를 float64로 변환
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)
#int1을 int32로 변환
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)
#float를 int32로 변환
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)



[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


#ndarray 생성
대규모의 데이터 초기화 혹은 데이터 생성

##1. arange() 
array를 range로 표현, 0부터 함수 인자 값 -1까지의 값 순차적 표현




In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) 
# 1차원 ndarray값을 만듦 여기서는 stop값만 부여했으나, range와 유사하게 start값도 부여해 0이 아닌 다른 값부터 시작할 수 있음.

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


##2. zeros()
모든 값을 0으로 채워 해당 shape를 가진 ndarray를 반환


##3. ones() 
모든 값을 1로 채움
-> 함수 인자로 dtype를 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채움

In [ ]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# reshape()
ndarray의 특정 차원 및 크기로 변환 



In [ ]:
# 0~9까지의 1차원 ndarray -> 2로우X5칼럼 2차원 ndarray로 변환


# 0~9까지의 1차원 ndarray -> 5로우X2칼럼 2차원 ndarray로 변환

In [ ]:
array1 = np.arange(10)
print('array:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1.reshape(4,3)
#reshape()는 지정된 사이즈로 변경이 불가능하면 오류 발생
# cf) (10,)를 (4,3) shape로 변경할 수 없음 


array:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: ignored

In [ ]:
#reshape() 인자 -1 적용
# ndarray와 호환되는 새로운 shape로 변환해줌

array1 = np.arange(10)
print(array1)

array2= array1.reshape(-1,5)
print('array2 shape:', array2.shape)
#로우 인자가 -1 칼럼 인자가 5임 array1과 호환될 수 있는 2차원 ndarray로 변환하되, 고정된 5개의 칼럼에 맞는 로우를 자동으로 생성해 변환
#따라서, 2X5의 2차원 ndarray로 변환

array3 = array2.reshape(5,-1)
print('array3 shape:', array3. shape)
#고정된 5개의 로우에 맞는 칼럼은 2이므로 5X2의 2차원 ndarray로 반환

#error 발생 건
array1= np.arange(10)
array4 = array1.reshape(-1,4)

#reshape의 -1 인자 빈출 사용법
#reshape(-1,1) : 원본 ndarray는 2차원, 여러개의 로우를 가져도 반드시 1개 칼럼
#여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


ValueError: ignored

# tolist() 
ndarray는 tolist() 메서드를 이용해 print 시, 시각적으로 보기 편하려고 리스트 자료형으로 변환 





In [ ]:
#reshape(-1,1)이용 #무조건 2차원으로 바꿔줌

array1 = np.arange(8) #1차원 
array3d = array1.reshape((2, 2, 2)) #3차원
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5= array3d.reshape(-1,1) #2차원
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1) #2차원
print('array6:\n', array6.tolist()) #리스트로 바꿔줌
print('array5 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


# ndarray 인덱싱
*   특정 데이터 추출: 원하는 위치의 인덱스 값 지정 -> 해당 위치 데이터 반환
*   슬라이싱: 연속된 ndarray 추출 ':' 기호 사이의 시작 인덱스와 종료 인덱스 표시하면 시작 인덱스 ~ 종료인덱스 -1 위치 데이터의 ndarray 반환 
ex) 1:5면 1과 종료 인덱스 4까지 해당하는 ndarray 반환
*   팬시 인덱싱: 일정한 인덱싱 집합을 리스트 혹은 ndarray 형태로 지정하여 데이터의 ndarray 반환
*   불린 인덱싱: True/False 값의 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환 



In [ ]:
# 단차원 단일 값 추출
array1 = np.arange(start=1, stop=10) # 1부터 9까지의 1차원 ndarray 생성
print('array1:', array1) 
value = array1[2] #위치의 인덱스 값 []안에 입력,  3번째 index 위치의 데이터 값 의미
print('value:', value)
print(type(value)) #더 이상 ndarray 타입이 아니라 ndarray 내의 데이터 값을 의미 즉 int64형임
#인덱스 -1은 맨 뒤의 데이터 값 의미 -2는 맨 뒤에서 두 번째 있는 데이터 값

#데이터 값 수정
array1[0]=9
array1[8]=0
print('array1:', array1)

# 다차원 ndarray의 단일 값 추출 (2차원, 3차원 큰 차이 없음)
array1d= np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0 index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

#axis 0은 로우 방향의 축
#axis 1은 칼럼 방향의 축
# 넘파이에서는 로우와 칼럼 표현 쓰지 않음 즉, [row=0, col=1] 인덱싱은 [axis 0=0, axis 1=1]
# 3차원 ndarray는 axis 0 (행), axis 1(열), axis 2(높이)
#축 기반의 연산에서 axis 가 생략되면 axis 0을 의미함. 



array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0 index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


# 슬라이싱
*   ':' 연속한 데이터를 슬라이싱해서 추출 (시작 인덱스에서 종료 인덱스 -1의 위치에 있는 데이터의 ndarray를 반환)
*   단일 데이터값 추출을 제외, 슬라이싱/팬시 인덱싱/불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입임.






In [ ]:
# <<1차원 슬라이싱>>
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

# ':' 주의사항
# 1) 시작 인덱스 생략하면 맨 처음 인덱스인 0으로 간주
# 2) 종료 인덱스 생략하면 맨 마지막 인덱스로 간주
# 3) 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

#<<2차원 ndarray 슬라이싱>>
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0]) #2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환함 
#즉, array2d[0]와 같아짐 2차원에서 뒤에 오는 인덱스를 없애면 axis 0의 첫번째 로우 ndarray 반환

# 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환함
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)


[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


# 팬시 인덱싱
리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식



In [35]:
array1d =  np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0,1], 2]
print('array2d[[0,2], 2]=>', array3.tolist()) #(0,2),(1,2)로 적용 됨

array4 = array2d[[0,1], 0:2] #((0,0), (0,1)), ((1.0), (1,1))
print('array2d[[0,1], 0:2]=>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0, 1]]=>', array5.tolist()) #((0, :),(1, :))



array2d[[0,2], 2]=> [3, 6]
array2d[[0,1], 0:2]=> [[1, 2], [4, 5]]
array2d[[0, 1]]=> [[1, 2, 3], [4, 5, 6]]


# 불린 인덱싱 
*   조건 필터링과 검색 동시 가능/ for loop/if else 문보다 훨씬 간단함
*   ndarray의 인덱스를 지정하는 []내에 조건문 기재



In [39]:
array1d = np.arange(start=1, stop=10)
#[] 안에 array1d > 5 boolean indexing 적용

array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3) #저장된 인덱스 데이터 세트로 ndarray 조회

#작동원리 
array1d > 5
#False 값은 무시하고 True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환,
#즉, 인덱스[5,6,7,8]의 위치 인덱스에 해당하는 데이터 세트 [6,7,8,9] 반환

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

#같은 결과(직접 인덱스 집합)
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)


array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]
불린 인덱스로 필터링 결과: [6 7 8 9]


# 행렬 정렬

np.sort() *넘파이에서 sort() 호출 (원 행렬의 정렬된 행렬 반환)
 
ndarray.sort() *행렬 자체에서 sort() 호출 (원행렬 자체를 정렬한 형태로 반환하며 반환 값은 None)



In [42]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

#오름차순 정렬
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

#내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

#행렬 2차원 이상일 때 axis 축 값 설정
array2d = np.array([[8,12],
                    [7,1]])
#로우 방향 axis=0
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
#칼럼 방향 axis=1
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#정렬된 행렬의 인덱스를 반환
#argsort()

In [45]:
#오름차순
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

#내림차순
org_array=np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

# 문제) 시험 성적 순으로 학생 이름을 출력
# np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출.

import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]
성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


#선형대수 연산 - 행렬 내적과 전치 행렬 구하기



In [55]:
#행렬 내적(행렬 곱)
#np.dot()

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

#전치 행렬 (A^T) #transpose()
#행과 열 위치를 교환한 원소로 구성된 행렬

A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
A의 전치 행렬:
 [[1 3]
 [2 4]]
